---
output: html_document
---
# Missing values 


## load data & preprocess data
 
- replace -1, Unknown/ Non-Applicable to NA 
- convert 'Salary Estimate' to col: low_salary, high_salary, avg_salary
- convert 'employee' to col: lower_bound_employee, upper_bound_employee, avg_employee
```{r echo=FALSE}

# Basics
if(!require(dplyr)) install.packages("dplyr")
if(!require(tibble)) install.packages("tibble")
if(!require(tidyr)) install.packages("tidyr")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(forcats)) install.packages("forcats")
if(!require(patchwork)) install.packages("patchwork")
if(!require(scales)) install.packages("scales")
if(!require(readr)) install.packages("readr")
if(!require(ggthemes)) install.packages("ggthemes")
if(!require(ggrepel)) install.packages("ggrepel")
if(!require(GGally)) install.packages("GGally")
if(!require(plotly)) install.packages("plotly")
if(!require(forcats)) install.packages("forcats")
if(!require(stringr)) install.packages("stringr")

if(!require(ggpubr)) install.packages("ggpubr")
if(!require(PupillometryR)) install.packages("PupillometryR")
if(!require(ggridges)) install.packages("ggridges")
if(!require(RColorBrewer)) install.packages("RColorBrewer")
if(!require(magrittr)) install.packages("magrittr") # allow %<>%

if(!require(vcd)) install.packages("vcd")
if(!require(d3r)) install.packages("d3r")
if(!require(ggalluvial)) install.packages("ggalluvial")
if(!require(parcoords)) install.packages("parcoords")

# pair plot
if(!require(gridGraphics)) install.packages("gridGraphics")
if(!require(gridExtra)) install.packages("gridExtra")

library("data.table")
library(mi)
```

```{r echo=FALSE}
ds_data = fread('data/DataScientist.csv') 
ds_data %>%
  select(3:ncol(.)) %>%
  mutate_all(~ifelse(. %in% c("NA", -1, "Unknown", "Unknown / Non-Applicable"), NA, .))   %>%
  as_tibble %>%
  separate(`Salary Estimate`, into = c("low","high"), sep = "-",remove = T) %>%
  mutate(low_salary = as.numeric(str_extract(low, "\\d+")),
         high_salary = as.numeric(str_extract(high, "\\d+")),
         avg_salary = (low_salary + high_salary) / 2)  %>% 

  separate(Size, into = c("low_ppl","high_ppl"), sep = "to", remove = T) %>% 
  mutate(lower_bound_employee = as.numeric(str_extract(low_ppl, "\\d+")),
         upper_bound_employee = as.numeric(str_extract(high_ppl, "\\d+")),
         avg_employee= case_when(
           !is.na(lower_bound_employee) & is.na(upper_bound_employee) ~ lower_bound_employee,
           T ~ (lower_bound_employee + upper_bound_employee) / 2)) ->ds_data
```



```{r echo=FALSE}
head(ds_data)

```

## missing value by column:

```{r echo=FALSE}
colSums(is.na(ds_data)) %>%
  sort(decreasing = TRUE)
```

## choose first ten company 

```{r echo=FALSE, fig.width = 13}
n_row = nrow(ds_data)
variables = colnames(ds_data)

ds_data %>% 
  slice(1:10) %>%
  mutate_all( as.character) %>%
  relocate(`Company Name`, 1) %>%
  pivot_longer(2:ncol(.)) %>%
  mutate(missing = ifelse(is.na(value), T, F)) %>%

ggplot() +
  geom_tile(aes(x=name,
                y=`Company Name`,
                fill=factor(missing))) + 
  labs(x = 'variable', y = 'company')+
  scale_fill_manual(values = c("grey60", alpha( "cornflowerblue", 0.6))) +
  scale_alpha_manual(values = c(0.5, 0.9)) +
  theme(axis.text.x = element_text(angle = 20,hjust = 0.95,vjust = 0.95))
```

