---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Results
```{r echo=FALSE}
# Basics
if(!require(dplyr)) install.packages("dplyr")
if(!require(tibble)) install.packages("tibble")
if(!require(tidyr)) install.packages("tidyr")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(forcats)) install.packages("forcats")
if(!require(patchwork)) install.packages("patchwork")
if(!require(scales)) install.packages("scales")
if(!require(readr)) install.packages("readr")
if(!require(ggthemes)) install.packages("ggthemes")
if(!require(ggrepel)) install.packages("ggrepel")
if(!require(GGally)) install.packages("GGally")
if(!require(plotly)) install.packages("plotly")
if(!require(forcats)) install.packages("forcats")
if(!require(stringr)) install.packages("stringr")

if(!require(ggpubr)) install.packages("ggpubr")
if(!require(PupillometryR)) install.packages("PupillometryR")
if(!require(ggridges)) install.packages("ggridges")
if(!require(RColorBrewer)) install.packages("RColorBrewer")
if(!require(magrittr)) install.packages("magrittr") # allow %<>%

if(!require(vcd)) install.packages("vcd")
if(!require(d3r)) install.packages("d3r")
if(!require(ggalluvial)) install.packages("ggalluvial")
if(!require(parcoords)) install.packages("parcoords")

# pair plot
if(!require(gridGraphics)) install.packages("gridGraphics")
if(!require(gridExtra)) install.packages("gridExtra")

library("data.table")
library(mi)
```

```{r}
if(!require(stopwords)) install.packages("stopwords")
library("stopwords")
library(tidyverse)
library(tidytext)
library("wordcloud")
library("wordcloud2")
library(textstem)
library(rmarkdown)

median_ybh <- function(x) median(x,na.rm=T)
mean_ybh <- function(x) mean(x,na.rm = T)
```

```{r}

# Loading
library("readxl")
# xls files
data <- read_excel("data/clean_loc.xlsx")
split(data, data$job_type_yubinghong) -> datas
```

## Skill set vs salary
```{r}
# turn into lower case
data%>% 
  mutate(lower_jd = tolower(`Job Description`)) -> data
         
c("python", "sql", "hadoop", "mysql", "tensorflow", "numpy","pandas","machine[[:space:]]learning","excel","tensorflow",
"keras","pytorch","[[:space:]]ai[[:space:]]","data[[:space:]]visualization","business[[:space:]]strategy","database","spark","git","[[:space:]]c[[:space:]]","matlab","matplotlib","scipy","opencv","anaconda","spacy","nlp","java","[[:space:]]golang[[:space:]]","github","kaggle","tableau","java[[:space:]]script","[[:space:]]r[[:space:]]" ) ->tech_requires

for(tech_require in tech_requires){
  new_column_name = paste0("require_", tech_require)
  data %<>%
    mutate(!!sym(new_column_name) := ifelse(grepl(tech_require, 
                                                  `lower_jd`, 
                                                  ignore.case = T), 1, 0)) 
}
# " r " %in% 


c('scikit-learn','sklearn',"scikit[[:space:]]learn") -> tech_requires3

for(tech_require in tech_requires3){
  new_column_name = paste0("require_", tech_require)
  data %<>%
    mutate(!!sym(new_column_name) := ifelse(grepl(tech_require, 
                                                  `lower_jd`), 1, 0)) 
}


data %>% 
  mutate(require_sklearn = max(`require_scikit-learn`,
                               `require_sklearn`,
                               `require_scikit[[:space:]]learn`,
                               na.rm=T)) %>%
  select(-`require_scikit-learn`,
         -`require_sklearn`,
         `require_scikit[[:space:]]learn`)-> data_2

data_2 %>%
  writeEXCEL("data_2.xlsx")

data_2%>%
  filter(require_r !=0) %>%
  select(`Job Description`)  

data_2 %>%
  select(`Avg_salary(k)`, contains("require_")) %>%
  pivot_longer(2:ncol(.),
               names_to = "Tech") %>% 
  mutate(Tech = gsub("require_", "", Tech)) %>%
  mutate(Tech = gsub("[[:space:]]+", " ", Tech)) %>%
  mutate(Tech = gsub("\\[\\[\\:space\\:\\]\\]", " ", Tech)) %>%
  filter(value !=0) -> skill_data

skill_data %>%
  group_by(Tech)%>%
  summarise(freq=n())%>%
  arrange(-freq)-> skill_count

median_ybh <- function(x) median(x,na.rm=T)
#skill_data %>%
 # writeEXCEL("skill_data.xlsx")

skill_data %>%
  mutate(rank = fct_reorder(Tech, 
                            `Avg_salary(k)`, 
                            median_ybh))%>%
  ggplot(aes(x = rank,
      y = `Avg_salary(k)`, fill = rank))+
  geom_boxplot() +
  theme(axis.text.x = element_text(hjust=0.8, angle=30)) +
  center_title + 
  labs(title = "Skill set vs salary") +
  labs(x = "Skill set") +
  labs(y = "Average salary in k")

```

```{r}
#skill_count %>%
 # writeEXCEL("skill_count.xlsx")
```

## wordcloud for skillset
```{r}
skill_count %>% 
  arrange(-freq)%>% 
  ungroup() %>% 
  as.data.frame() -> df_word

rownames(df_word) <- df_word$Tech
wordcloud2(df_word , size = 2, shape = 'movie') 
```

## salary vs job title 
```{r}
data %>%
  drop_na(job_type_yubinghong)   %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0))  %>% 
  ggplot(aes(y=`Avg_salary(k)`, 
             x = job_type_yubinghong,
             fill = job_type_yubinghong)) +
  geom_boxplot() +
  labs(title = 'Average salary for job titles') + 
  labs(x = "Job titile") +
  labs(y = 'average salary in k unit ') +
  center_title
```
This plot compares salary for four job titles, filled with four colors to seperate the job title.

##
```{r}
data%>% 
  mutate(lower_jd = tolower(`Job Description`)) -> data

c("bacherlor" ,"master","phd")  -> academics

for(academic in academics){
  new_column_name = paste0("require_", academic)
  data %>%
    mutate(!!sym(new_column_name) := ifelse(grepl(academic, 
                                                  `lower_jd`), 1, 0))-> data_3
}


data_3%>%
  select(`Avg_salary(k)`, contains("require_")) %>%
  pivot_longer(2:ncol(.),
               names_to = "Academic") %>% 
  mutate(Tech = gsub("require_", "", Academic)) %>%
  #mutate(Tech = gsub("[[:space:]]+", " ", Tech)) %>%
  #mutate(Tech = gsub("\\[\\[\\:space\\:\\]\\]", " ", Tech)) %>%
  filter(value !=0) -> academic_data


median_ybh <- function(x) median(x,na.rm=T)

#academic_data %>%
#  writeEXCEL("skill_data.xlsx")

academic_data %>%
  mutate(ranking = fct_reorder(Academic, 
                            `Avg_salary(k)`, 
                            median_ybh))%>%
  ggplot(aes(x = ranking,
      y = `Avg_salary(k)`, fill = ranking))+
  geom_boxplot() +
  theme(axis.text.x = element_text(hjust=0.8, angle=30)) +
  center_title + 
  labs(title = "Skill set vs salary") +
  labs(x = "Skill set") +
  labs(y = "Average salary in k")

```

## company size vs salary 不行！重来
```{r}
data%>% 
  drop_na(Size)%>% 
  ggplot(aes(x=fct_reorder(Size, `Avg_salary(k)`,median_ybh), 
             y=`Avg_salary(k)`,fill = Size)) + 
  geom_boxplot() + 
  labs(title = 'Company size (employee number) vs salary') + 
  labs(y = "Salary") +
  labs(x = 'Average company employee') +
  center_title
  

```

```{r}
data%>% 
  drop_na(Size)%>% 
  ggplot(aes(y=fct_reorder(Size, `Avg_salary(k)`,median_ybh), 
             x=`Avg_salary(k)`)) + 
  geom_point() + 
  labs(title = 'Company size (employee number) vs salary') + 
  labs(y = "Salary") +
  labs(x = 'Average company employee') +
  center_title
  

#found year

```




```{r}
data%>% 
  drop_na(Industry)%>% 
  group_by(Industry)%>% 
  summarise(n = n()) %>%
  arrange(-n) %>%
  mutate(industry_label = ifelse(min_rank(-n) <=10, Industry, "Others") %>%
  factor %>% fct_relevel("Others", after=Inf)) -> industry_to_label_map

data %>%
  left_join(industry_to_label_map) -> industry_data
  

industry_data%>% 
  ggplot(aes(y=fct_reorder(industry_label, `Avg_salary(k)`,median_ybh) %>%
               fct_relevel("Others", after=Inf),
             x=`Avg_salary(k)`, fill = industry_label)) + 
  geom_density_ridges(alpha=0.6)  + 
  labs(title = 'Industry vs salary') + 
  labs(y = "Salary") +
  labs(x = 'Industry') +
  center_title + 
  theme_ridges() + 
  theme(legend.position = "none") 

```


```{r}

data%>% 
  drop_na(Sector)%>% 
  group_by(Sector)%>% 
  summarise(n = n()) %>%
  arrange(-n) %>%
  mutate(industry_label = ifelse(min_rank(-n) <=10, Industry, "Others") %>%
  factor %>% fct_relevel("Others", after=Inf)) -> industry_to_label_map

data %>%
  left_join(industry_to_label_map) -> industry_data
  

industry_data%>% 
  ggplot(aes(y=fct_reorder(industry_label, `Avg_salary(k)`,median_ybh) %>%
               fct_relevel("Others", after=Inf),
             x=`Avg_salary(k)`, fill = industry_label)) + 
  geom_density_ridges(alpha=0.6)  + 
  labs(title = 'Industry vs salary') + 
  labs(y = "Salary") +
  labs(x = 'Industry') +
  center_title + 
  theme_ridges() + 
  theme(legend.position = "none") 

data%>% 
  drop_na(Sector)%>% 
  ggplot(aes(x=fct_reorder(Sector, `Avg_salary(k)`,median_ybh),
             y=`Avg_salary(k)`,fill = Sector)) + 
  geom_boxplot() + 
  labs(title = 'Company size (employee number) vs salary') + 
  labs(y = "Salary") +
  labs(x = 'Average company employee') +
  center_title
```


```{r}
data%>% 
  drop_na(Founded)%>% 
  ggplot(aes(x=`Founded`,
             y=`Avg_salary(k)`)) +
  facet_wrap(~job_type_yubinghong) + 
  geom_point(alpha = 0.15,size = 0.25) + 
  labs(title = 'Company size (employee number) vs salary') + 
  labs(y = "Salary") +
  labs(x = 'Average company employee') +
  center_title
```

revenue vs salary

```{r}

data %>% 
  drop_na(`job_type_yubinghong`)%>% 
  group_by(`job_type_yubinghong`,`Name of Company`)%>% 
  summarise(n = n()) %>%
  arrange(-n) 
  summarise(salary_jobT= mean_ybh(`Avg_salary(k)`))


data%>% 
  drop_na(`Name of Company`)%>% 
  group_by(`Name of Company`)%>% 
  summarise(n = n()) %>%
  arrange(-n) %>%
  mutate(company_label = ifelse(min_rank(-n) <=20, `Name of Company`, "Others") %>%
  factor %>% fct_relevel("Others", after=Inf)) -> company_to_label_map

data %>%
  left_join(company_to_label_map) -> company_data 

company_data%>% 
  ggplot(aes(x=mean_job$salary_jobT,
             y=fct_reorder2(state, mean_job$salary_jobT, .desc = FALSE) 

ggplot(belts, aes(x = fatalities, y = fct_reorder2(state, year == 1997, fatalities, .desc = FALSE), color = year)) +
  geom_point() +
  ggtitle("# of fatalities per million traffic miles") +
  ylab("") +
  theme_linedraw()


  geom_density_ridges(alpha=0.6)  + 
  labs(title = 'Company vs salary') + 
  labs(y = "Salary") +
  labs(x = 'Company') +
  center_title + 
  theme_ridges() + 
  theme(legend.position = "none") 
```


title vs industry/sector


