# Conclusion

There are several limitations on our study. Most of them are data-related. First of all, we use data provided by Glassdoor, a job-finding website where companies and employees post their advertisements and their resumes. This lead to a problem. The data that we collect could be a bit off from the real situation in the industry. For example, a company may put a higher salary amount on their advertisements while the real salaries are lower. And many of their job descriptions are the minimal qualification needed for this job, but they give offers to applicants who are overqualified. That lead to a problem that the status that we examined might be different from the real situation in the industry. Therefore in the future, we want to collect data from more authentic sources. Corporate Annual Report is a good example. All data provided by their reports are authentic and reliable. 
After investigating all possible factors provided in the dataset, now we have a clear clue about what make a job high-paid. First of all, jobs in IT, Media and Biotech industries pay more. Secondly, skill sets largely determine the salary level. Some of the high paid jobs require employees to have a good grip of advanced skills such as R, SQL and Machine Learning. Therefore, as job seekers in data related fields are encouraged to pursue a higher degree and try to comprehend as more skills as possible. 