# Introduction


Name: Binghong Yu(by2325), Huanyu Jiang(hj2593), Huaizhi Ge(hg2590)

We choose this topic because data science is our shared major. Over the last ten years, data science has progressed considerably. Data science is an enthralling, lucrative, and rapidly expanding discipline. Data scientists organize and analyze enormous amounts of information, look for trends, and make predictions. Data science majored students are required in nearly every field, including business, finance, science, health, and government. As students who are looking for a position in job market, the first thing concerning us is the salary of a job position. As a data science student, we are interested in learning the salary patterns in different data science positions. We do so with the techniques we learned in class. After looking at all of the variables in the dataset, we will have a good idea of what makes a job well-paid. To begin with, positions in the IT, media, and biotech industries pay well. Second, the salary level is mostly determined by skill sets. Some of the higher-paying occupations demand that individuals have a strong grasp of advanced abilities like R, SQL, and Machine Learning. As a result, job seekers in data-related professions should consider pursuing a higher degree and learning as many skills as feasible. More details will bbe discusses in their respectove sections in thsi book.

